### ISSUE TITLE
Folder search works, search in said folder does not.

### ISSUE THREAD

**Issue by WybeBosch** [alfredapp/dynamic-file-search#1]
**Issue:** 
When using the ff workflow, i can properly select a folder
but on the second popup no results show up whatever i type. Except for the folder i have just selected.

**Example:**
1. type ff desktop
2. select desktop
3. second prompt opens to search within the desktop
4. (in the description prompt it properly says "Search for files within [full path to said folder")
5. Type any letter or filename
6. No results show up
7. Type the name of the folder you are searching in
8. It shows up

Am i using the workflow incorrectly? or did an update change something?

**Context:**
The files im searching for on the desktop do properly show up both in apple Spotlight, 
and if i just use the alfred "find" command. 

**What am i trying todo?:**
But i have a folder that contains all my websites, and those websites contain files that are the same name for each project. 
So im trying to open a specific file that has the same name across these folders. 
By filtering the folder first.

When using the troubleshooting command aswell, it shows all is well
(Tho that is more related to general search than this specific workflow)

```
Starting Diagnostics...

File: '_bootstrap.scss'
Path: '/Users/wybe/Local Sites/lhv/app/public/htdocs/wp-content/themes/theme-fusion/assets/scss/vendor'

-----------------------------------------------------------

Check file cache database...

✅ File cache integrity is ok

-----------------------------------------------------------

Check if file is readable...

✅ Alfred has permissions to read this file.

Unix Permissions: 420
Underlying Type: NSFileTypeRegular
Extended Attributes: (
)

-----------------------------------------------------------

Check if volume '/' is indexed by macOS...

✅ Indexing is enabled on this drive

-----------------------------------------------------------

Check direct file metadata...

⚠️ Direct metadata available, but content type may be incorrect

Display Name: _bootstrap.scss
 Other Names: 
Content Type: dyn.ah62d4rv4ge81g25xsq
   Last Used: 

-----------------------------------------------------------

Check mdls file metadata...

✅ Metadata contains required items

_kMDItemDisplayNameWithExtensions  = "_bootstrap.scss"
kMDItemContentCreationDate         = 2023-04-05 13:58:18 +0000
kMDItemContentCreationDate_Ranking = 2023-09-02 00:00:00 +0000
kMDItemContentModificationDate     = 2023-04-05 13:58:18 +0000
kMDItemContentType                 = "dyn.ah62d4rv4ge81g25xsq"
kMDItemContentTypeTree             = (
    "public.item",
    "dyn.ah62d4rv4ge81g25xsq",
    "public.data"
)
kMDItemDateAdded                   = 2023-09-02 11:16:11 +0000
kMDItemDisplayName                 = "_bootstrap.scss"
kMDItemDocumentIdentifier          = 0
kMDItemFSContentChangeDate         = 2023-04-05 13:58:18 +0000
kMDItemFSCreationDate              = 2023-04-05 13:58:18 +0000
kMDItemFSCreatorCode               = ""
kMDItemFSFinderFlags               = 0
kMDItemFSHasCustomIcon             = (null)
kMDItemFSInvisible                 = 0
kMDItemFSIsExtensionHidden         = 0
kMDItemFSIsStationery              = (null)
kMDItemFSLabel                     = 0
kMDItemFSName                      = "_bootstrap.scss"
kMDItemFSNodeCount                 = (null)
kMDItemFSOwnerGroupID              = 20
kMDItemFSOwnerUserID               = 501
kMDItemFSSize                      = 974
kMDItemFSTypeCode                  = ""
kMDItemInterestingDate_Ranking     = 2023-04-05 00:00:00 +0000
kMDItemKind                        = "Document"
kMDItemLogicalSize                 = 974
kMDItemPhysicalSize                = 4096

-----------------------------------------------------------

Check file is in search scope...

✅ File exists within Alfred's default search scope

-----------------------------------------------------------

Check MDQuery file search...

✅ macOS returned a match for this file in your search scope.

File Search Results for search scope (
    "[17] /System/Volumes/Data/Users/wybe/Local Sites/lhv/app/public/htdocs/wp-content/themes/theme-fusion/assets/scss/vendor/_bootstrap.scss"
)

File Search Results for ~/ (
)

File Search Results for / (
    "[17] /System/Volumes/Data/Users/wybe/Local Sites/lhv/app/public/htdocs/wp-content/themes/theme-fusion/assets/scss/vendor/_bootstrap.scss"
)

-----------------------------------------------------------

✅ Troubleshooting passed

⚠️ There were 1 warning(s)

```

**Comment by vitorgalvao** [comment]
> When using the troubleshooting command aswell, it shows all is well

It does show an error:

```
⚠️ Direct metadata available, but content type may be incorrect
```

Though I notice you had a JPEG in there before. The content type tree does seem incorrect:

```
kMDItemContentType                 = "dyn.ah62d4rv4ge81g25xsq"
kMDItemContentTypeTree             = (
    "public.item",
    "dyn.ah62d4rv4ge81g25xsq",
    "public.data"
)
```

It should be something like:

```
kMDItemContentType                 = "com.sass-lang.scss"
kMDItemContentTypeTree             = (
    "com.sass-lang.scss",
    "public.source-code",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

To clarify, is it only the SCSS files that you’re failing to find?

**Comment by WybeBosch** [comment]
- While im specifically trying to find scss
- This issues occurs when trying to find Any file type using the 2nd part of the workflow

- Previously i had indeed included the troubleshooting log for an image on desktop
But then i changed it to my actual use case. (https://pastebin.com/mv2bvMfU)

- It is a Fresh install of the workflow, i have not modified it.

And while yes it does indeed show a warning for metadata of my .scss files, 
even when trying to find other files it does nothing. 

**Perhaps this gif will illustrate my issue** 
![Alfred Workflow FF](https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/6e47f15b-790a-411f-85ec-9930a581722b)


While using a normal search it can find that file on the desktop 
<img width="1274" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/c468caab-0783-43fe-9b6b-32c533b14611">

<img width="1020" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/ac1fce50-122b-47f2-8242-69e99961da7a">

**Comment by vitorgalvao** [comment]
Was it [installed from the Gallery](https://alfred.app/workflows/alfredapp/dynamic-file-search/)?

Try creating a new folder on your Desktop and making a new text file. Is that found? Please try it with [the debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) running and post the output, so we can see what’s happening.

Also, what’s your exact version of Alfred?

**Comment by WybeBosch** [comment]
It was installed from 
https://alfred.app/workflows/alfredapp/dynamic-file-search/

This is the newly created file ran trough the troubleshooter
https://pastebin.com/iiAu22N7

Same as before the file can be found by Spotlight, by alfred "find" and by just typing the filename in "base" alfred

![Alfred workflow test2](https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/eb12aa0b-c742-403b-9d82-70018da6a142)

My Exact version of alfred is Alfred 5.1.4 [2195]
[Alfred Diagnostics 2024-02-06 at 15.51.17.alfreddiagnostics.txt](https://github.com/alfredapp/dynamic-file-search-workflow/files/14181917/Alfred.Diagnostics.2024-02-06.at.15.51.17.alfreddiagnostics.txt)

**Comment by vitorgalvao** [comment]
Could you try [this version](https://github.com/alfredapp/dynamic-file-search-workflow/files/14182834/Dynamic.File.Search.alfredworkflow.zip)?

**Comment by WybeBosch** [comment]
- uninstalled the currently installed version
- force quit alfred
- re open aflred
- installed your new version where you changed the fields of the second search to have different metadata field searches

Still the same result unfortunately.

It almost feels like something silly that a extra / is needed to force it to actually search in the chosen folder or something
```
{
    "variables" : {
      "folder": "{query}/"
}
```
Something like that, but thats not how the folder search works in alfred probably.

**Comment by vitorgalvao** [comment]
> but thats not how the folder search works in alfred probably.

Indeed. That part isn’t even relevant to the functionality (that’s for the subtitle only), what matters is the `scope` part.

Does the issue only happen when you select the Desktop in the first step? What happens when:

* You select a folder that is inside the Desktop? E.g the `alfredfolder` above.
* You select any other folder *which is not a direct descendent of the home folder*? E.g. `~/Local Sites/lhv` would be valid, but not `~/Local Sites`.

Also:

* What does System Settings → Sire & Spotlight → Spotlight Privacy… look like? Do you have anything in there?
* Did you use the [Ignore in Alfred](https://alfred.app/workflows/alfredapp/ignore-in-alfred/) workflow anywhere, or tagged any file with `alfred:ignore`?
* What macOS version are you on?

Finally, create a new workflow with a [File Filter Input](https://www.alfredapp.com/help/workflows/inputs/file-filter/). Does that work?

**Comment by WybeBosch** [comment]
Apologies for the delayed response. 

- Same issue when selecting a folder Inside desktop such as alfred folder
![alfredfolder](https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/f7d5d613-71fb-47e0-9d3c-592641789472)

- Searching within LHV also has the same result
![lhv folder](https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/8d1cee28-8fa0-4ed4-b6ef-34518d77b054)
*note: the 2nd part never returns any file/folder results except for the "selected folder" 

 - System settings
<img width="493" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/e5e49577-47c1-417a-9f90-981476faef16">

<img width="531" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/f57483fa-a716-49ab-9279-4e20b57b4294">

- Im not using the ignore in alfred somewhere, since the file can be found by using the Normal alfred search.
- Im on macOS Ventura 13.5.2

Normal file filter doesnt seem to be working either.

<img width="732" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/6c237b6a-46b1-48a7-b922-91204d20e009">
<img width="696" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/f48f271a-10e8-4557-98b4-0181954c3ce8">
<img width="720" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/e129e878-fdc3-4315-8bf7-9c40715b988c">
<img width="695" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/44dc9e8a-e3dd-483c-833d-8baec54956a3">
<img width="685" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/884e4879-f7c2-4733-8638-370cfc4634a6">


It seems it has the same behavior, where it cant display any files, but can display the "scoped" folders.

<img width="861" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/2ba5e621-6eef-4608-9602-98af4b6cd9dd">
<img width="749" alt="image" src="https://github.com/alfredapp/dynamic-file-search-workflow/assets/40889930/da91defb-ad64-4ac2-8b47-5709063c1687">

**Comment by vitorgalvao** [comment]
Please [rebuild you index](https://www.alfredapp.com/help/troubleshooting/indexing/#rebuild).

**Comment by WybeBosch** [comment]
Hey there, 

After some trial and error i have rebuild my index. (Used both the reset options of the alfred index reset)
Now the Workflow is working again as intended! :) 

I still think it is a bit strange that i could find the file if i search alfred normally, 
but that i could not find it via the workflow (appearntly because of index issues)

You would think if i had index issues that the file woudnt show up in the normal Alfred Search either... 

Regardless, thank you for your time in checking this issue with me. 
I think this issue can be closed.

**Comment by vitorgalvao** [comment]
The idea when trying with a new File Filter was to have a new clean one without modification, but because restrictions were added, a broken index would not have shown those, while the more generic unrestricted search would.

Glad you’re sorted. Have a nice weekend!
